source/Ellucian.Web.Student/Ellucian.Web.Student/Areas/TimeManagement/Controllers/TimeApprovalController.cs
//Copyright 2016 Ellucian Company L.P. and its affiliates.
using Ellucian.Colleague.Dtos.HumanResources;
using Ellucian.Colleague.Dtos.TimeManagement;
using Ellucian.Web.Adapters;
using Ellucian.Web.Mvc.Filter;
using Ellucian.Web.Mvc.Models;
using Ellucian.Web.Student.Areas.TimeManagement.Models;
using Ellucian.Web.Student.Filters;
using Ellucian.Web.Student.Infrastructure;
using Ellucian.Web.Student.Models;
using Newtonsoft.Json;
using slf4net;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Ellucian.Web.Student.Areas.TimeManagement.Controllers
{

     [Authorize]
     [OutputCache(CacheProfile = "NoCache")]
     public class TimeApprovalController : SharedController
     {
          /// <summary>
          /// Creates an instance of TimeApprovalController
          /// </summary>
          /// <param name="adapterRegistry">adapter registry helper; injected by the framework</param>
          /// <param name="settings">settings helper; injected by the framework</param>
          /// <param name="logger">logging helper; injected by the framework</param>
          public TimeApprovalController(IAdapterRegistry adapterRegistry, Settings settings, ILogger logger)
               : base(adapterRegistry, settings, logger)
          {

          }

          [LinkHelp]
          [PageAuthorize("timeApproval")]
          public ActionResult Index()
          {
               ViewBag.Title = "Time Approval";
               ViewBag.CssAfterOverride = new List<string>();


               return View("~/Areas/TimeManagement/Views/TimeApproval/TimeApproval.cshtml");
          }

          [HttpGet]
          [PageAuthorize("timeApproval")]
          public async Task<JsonResult> GetSummaryApprovalDataAsync()
          {
               try
               {
                    // get necessary information
                    var Timecards2Task = ServiceClient.GetTimecards2Async();
                    var timecardStatusesTask = ServiceClient.GetLatestTimecardStatuses();
                    var positionsTask = ServiceClient.GetPositionsAsync();
                    var personPositionsTask = ServiceClient.GetPersonPositionsAsync();
                    var personPositionWagesTask = ServiceClient.GetPersonPositionWagesAsync();
                    var payCyclesTask = ServiceClient.GetPayCyclesAsync();
                    var commentsTask = ServiceClient.GetTimeEntryCommentsAsync();
                    var personEmploymentStatusesTask = ServiceClient.GetPersonEmploymentStatusesAsync();
                    var humanResourcesDemographicsTask = ServiceClient.GetHumanResourceDemographicsAsync();

                    await Task.WhenAll(Timecards2Task, timecardStatusesTask, positionsTask, personPositionsTask, personPositionWagesTask, payCyclesTask, commentsTask, personEmploymentStatusesTask, humanResourcesDemographicsTask);

                    var timecards = Timecards2Task.Result;
                    var timecardStatuses = timecardStatusesTask.Result;
                    var positions = positionsTask.Result.ToList();
                    var personPositions = personPositionsTask.Result.ToList();
                    var personPositionWages = personPositionWagesTask.Result.ToList();
                    var payCycles = payCyclesTask.Result;
                    var comments = commentsTask.Result;
                    var personEmploymentStatuses = personEmploymentStatusesTask.Result;
                    var humanResourcesDemographicsDtos = humanResourcesDemographicsTask.Result;

                    var employeeDictionary = humanResourcesDemographicsDtos.ToDictionary((hrd) => hrd.Id);

                    var supervisorPositionQuery = new PositionQuery(CurrentUser.PersonId, personPositions, positions, personPositionWages, payCycles, true);
                    var approverQuery = new ApproverQuery(timecards, timecardStatuses, payCycles, comments);

                    var timeApprovalModel = new ApprovalSummaryModel(supervisorPositionQuery, approverQuery, positions, personPositions, employeeDictionary, personEmploymentStatuses);

                    var payCycleDict = payCycles.ToDictionary(p => p.Id);
                    var overtimeTasks = timeApprovalModel.PayPeriodModels
                        .SelectMany(pm =>
                            {
                                 PayCycle payCycle = null;
                                 //var normalizePayPeriodStartDate = ;
                                 //var normalizePayPeriodEndDate = ;

                                 //if the paycycle object for the given id exists (which it should)
                                 //and the normalized
                                 if (payCycleDict.TryGetValue(pm.PayCycleId, out payCycle))
                                 {
                                      return pm.EmployeeModels.SelectMany(em =>
                                          TimeManagementUtilities.Weeks(
                                              pm.PeriodStartDate.NormalizeToStartDayOfWeek(payCycle.WorkWeekStartDay),
                                              pm.PeriodEndDate.NormalizeToEndDateOfWeek((DayOfWeek)(int)payCycle.WorkWeekStartDay + 6 % 7))
                                          .Where(w => w.Last() <= pm.PeriodEndDate) //only include overtime for weeks that end in this pay period. overtime is paid in the pay period in which the week ends
                                          .Select(w =>
                                          ServiceClient.CalculateOvertime(new OvertimeQueryCriteria()
                                          {
                                               PersonId = em.EmployeeId,
                                               PayCycleId = pm.PayCycleId,
                                               EndDate = w.Last(),
                                               StartDate = w.First()
                                          })));
                                 }
                                 else
                                 {
                                      return null;
                                 }
                            })
                            .Where(task => task != null).ToList();


                    await Task.WhenAll(overtimeTasks);

                    var taskGrouping = overtimeTasks.GroupBy(t => new Tuple<DateTime, string>(t.Result.EndDate, t.Result.PayCycleId));

                    foreach (var taskGroup in taskGrouping)
                    {
                         var payPeriodModel = timeApprovalModel.PayPeriodModels.FirstOrDefault(p => p.PeriodEndDate >= taskGroup.Key.Item1 && p.PeriodStartDate <= taskGroup.Key.Item1 && p.PayCycleId == taskGroup.Key.Item2);
                         if (payPeriodModel != null)
                         {
                              foreach (var task in taskGroup)
                              {
                                   var employeeModel = payPeriodModel.EmployeeModels.FirstOrDefault(e => e.EmployeeId == task.Result.PersonId);
                                   if (employeeModel != null)
                                   {
                                        employeeModel.OvertimeHours += (decimal)task.Result.Thresholds.Sum(t => t.TotalOvertime.TotalHours);
                                   }
                              }
                         }
                    }


                    return Json(new StandardJsonResult(timeApprovalModel), JsonRequestBehavior.AllowGet);
               }
               catch (Exception e)
               {
                    var message = "Something went wrong retrieving data or creating models: " + e.Message + Environment.NewLine + e.StackTrace;
                    Logger.Error(e, message);
                    return Json(new StandardJsonResult(statuscode: HttpStatusCode.BadRequest, message: message), JsonRequestBehavior.AllowGet);
               }

          }

          [HttpGet]
          [PageAuthorize("timeApproval")]
          public async Task<JsonResult> GetDetailApprovalDataAsync(string personId, string payCycleId, string payPeriodEndDate)
          {
               if (string.IsNullOrWhiteSpace(personId))
               {
                    var message = "personId is required";
                    Logger.Error(message);
                    return Json(new StandardJsonResult(statuscode: HttpStatusCode.BadRequest, message: message), JsonRequestBehavior.AllowGet);
               }
               if (string.IsNullOrWhiteSpace(payCycleId))
               {
                    var message = "payCycleId is required";
                    Logger.Error(message);
                    return Json(new StandardJsonResult(statuscode: HttpStatusCode.BadRequest, message: message), JsonRequestBehavior.AllowGet);
               }
               if (string.IsNullOrWhiteSpace(payPeriodEndDate))
               {
                    var message = "payPeriodEndDate is required";
                    Logger.Error(message);
                    return Json(new StandardJsonResult(statuscode: HttpStatusCode.BadRequest, message: message), JsonRequestBehavior.AllowGet);
               }

               DateTime periodEndDate;
               if (!DateTime.TryParse(payPeriodEndDate, out periodEndDate))
               {
                    var message = "unable to parse payPeriodEndDate";
                    Logger.Error(message);
                    return Json(new StandardJsonResult(statuscode: HttpStatusCode.BadRequest, message: message), JsonRequestBehavior.AllowGet);
               }

               try
               {


                    var positionQuery = await ServiceClient.GetPositionQueryAsync(GetEffectivePersonId(), personId, false);
                    //get relevant PayPeriod
                    var payCycle = positionQuery.GetPayCycle(payCycleId);

source/Ellucian.Web.Student/Ellucian.Web.Student/Areas/TimeManagement/Views/TimeApproval/TimeApproval.cshtml
@*Copyright 2016 Ellucian Company L.P. and its affiliates*@

@Html.Partial("_ActionUrlDefinitions")

@using Ellucian.Web.Student.Helpers;
@{
    @Html.RenderDevStyleBundle("/Areas/TimeManagement/Build/time.approval.bundle.min.css");
    @Html.RenderDevScriptBundle("/Areas/TimeManagement/Build/time.approval.bundle.js");

    @Html.RenderProductionStylesheetBundle("/Areas/TimeManagement/Build/time.approval.bundle.min.css");
    @Html.RenderProductionScriptBundle("/Areas/TimeManagement/Build/time.approval.bundle.min.js");
    
}


<div id="time-approval-application">
    <!-- ko if: currentViewComponentName -->
    <div id="page-description" class="esg-page-header">
        <h2 class="esg-page-header__title">@Resources.TimeApproval.TimeApprovalPageDescription</h2>
        <a class="esg-page-header__subtitle esg-page-header__subtitle--backlink" href=" #" data-bind="visible: currentViewComponentName() !== 'summary-view-component'">
            <span class="esg-icon__container esg-page-header__icon" aria-hidden="true">
                <svg class="esg-icon esg-icon--left">
                    <use xlink:href="#icon-arrow"></use>
                </svg>
            </span>@Resources.TimeApproval.TimeApprovalPageDescription
        </a>
    </div>
    <!-- /ko -->

    <div class="full-width column-nine">

        <!-- ko if: currentViewComponentName -->
        <!-- ko component: {
            name: currentViewComponentName,
            params: currentViewComponentParams
        } -->
        <!-- /ko -->
        <!-- /ko -->


    </div>
</div>

source/Ellucian.Web.Student/Ellucian.Web.Student/Areas/TimeManagement/Views/TimeApproval/_ActionUrlDefinitions.cshtml
@*Copyright 2016 Ellucian Company L.P. and its affiliates.*@

<script type="text/javascript">
    window.Ellucian = window.Ellucian || {};
    window.Ellucian.TimeApproval = window.Ellucian.TimeApproval || {};
    window.Ellucian.TimeApproval.ActionUrls = {
        getSummaryApprovalDataUrl: '@Url.Action("GetSummaryApprovalDataAsync", "TimeApproval")',
        getDetailApprovalDataUrl: '@Url.Action("GetDetailApprovalDataAsync", "TimeApproval")',
        submitTimecardStatusUrl: '@Url.Action("SubmitTimecardStatusAsync", "TimeApproval")',
        submitTimecardStatusesUrl: '@Url.Action("SubmitTimecardStatusesAsync", "TimeApproval")',
        createTimeEntryCommentsUrl: '@Url.Action("CreateTimeEntryCommentsAsync", "TimeApproval")',
        postOvertimeQueryUrl: '@Url.Action("PostOvertimeQueryAsync", "TimeApproval")'
    }

    window.Ellucian.appUrl = '@Url.Content("~")';
</script>